network:
  ethernets:
    ens3:
      addresses:
        - 192.168.122.14/24
      gateway4: 192.168.122.1
      nameservers:
        addresses: [8.8.8.8]
    ens4:
      addresses:
        - 10.128.0.2/27
        - fc00:0:f800::2/64
      routes:
        - to: 10.0.0.0/8
          via: 10.128.0.1 
        - to: fc00:0000::/32
          via: fc00:0:f800::1 
          on-link: true
    ens5:
      addresses:
        - 10.128.0.130/27
        - fc00:0:f800:4::2/64
      routes:
        - to: 10.0.0.0/8
          via: 10.128.0.129 
        - to: fc00:0000::/32
          via: fc00:0:f800:4::1 
          on-link: true
    ens6:
      addresses:
        - 10.128.1.2/27
        - fc00:0:f800:8::2/64
      routes:
        - to: 10.0.0.0/8
          via: 10.128.1.1 
        - to: fc00:0000::/32
          via: fc00:0:f800:8::1 
          on-link: true
    ens7:
      addresses:
        - 10.128.1.130/27
        - fc00:0:f800:c::2/64
      routes:
        - to: 10.0.0.0/8
          via: 10.128.1.129 
        - to: fc00:0000::/32
          via: fc00:0:f800:c::1 
          on-link: true
  version: 2
