network:
  ethernets:
    ens3:
      addresses:
        - 192.168.122.15/24
      gateway4: 192.168.122.1
      nameservers:
        addresses: [8.8.8.8]
    ens4:
      addresses:
        - 10.128.0.34/27
        - fc00:0:f800:1::2/64
      routes:
        - to: 10.0.0.0/8
          via: 10.128.0.33 
        - to: fc00:0000::/32
          via: fc00:0:f800:1::1 
          on-link: true
    ens5:
      addresses:
        - 10.128.0.162/27
        - fc00:0:f800:5::2/64
      routes:
        - to: 10.0.0.0/8
          via: 10.128.0.161 
        - to: fc00:0000::/32
          via: fc00:0:f800:5::1 
          on-link: true
    ens6:
      addresses:
        - 10.128.1.34/27
        - fc00:0:f800:9::2/64
      routes:
        - to: 10.0.0.0/8
          via: 10.128.1.33 
        - to: fc00:0000::/32
          via: fc00:0:f800:9::1 
          on-link: true
    ens7:
      addresses:
        - 10.128.1.162/27
        - fc00:0:f800:d::2/64
      routes:
        - to: 10.0.0.0/8
          via: 10.128.1.161 
        - to: fc00:0000::/32
          via: fc00:0:f800:d::1 
          on-link: true
  version: 2
