network:
  ethernets:
    eth0: 
      dhcp4: true

    eth1: 
      addresses: 
        - 10.10.16.2/24
        - fc00:0:f800:8000::2/64
      routes:
        - to: fc00:0:fe00::/48
          via: fc00:0:f800:8000::1

    eth2: 
      addresses: 
        - 10.10.20.2/24
        - fc00:0:f800:8004::2/64
      routes:
        - to: fc00:0:fe01::/48
          via: fc00:0:f800:8004::1

    eth3: 
      addresses: 
        - 10.10.24.2/24
        - fc00:0:f800:8008::2/64
      routes:
        - to: fc00:0:fe02::/48
          via: fc00:0:f800:8008::1

    eth4: 
      addresses: 
        - 10.10.28.2/24
        - fc00:0:f800:800c::2/64
      routes:
        - to: fc00:0:fe03::/48
          via: fc00:0:f800:800c::1

  version: 2