---

# ansible-playbook -i hosts srv6-pingtest-playbook.yml 

- name: Build network namespaces, execute tcpdump, and run ping tests
  hosts: localhost
  become: true
  tasks:

    - name: add ipv6 addr to br16
      command: "ip -6 addr add fc00:0:f800::2/64 dev br16"
      ignore_errors: yes

    - name: add ipv6 addr to br22
      command: "ip -6 addr add fc00:0:f800:2::2/64 dev br22"
      ignore_errors: yes

    - name: add ipv6 routes to localhost for Vrf1
      command: "ip -6 route add fc00:0:f800:4::/64 via fc00:0:f800::1 dev br16"
      ignore_errors: yes

    - name: add ipv6 routes to localhost for Vrf2
      command: "ip -6 route add fc00:0:f800:7::/64 via fc00:0:f800:3::1 dev br19"
      ignore_errors: yes

    - name: build Vrf1 network namespace connected to 09-leaf Ethernet8
      command: "files/vrf1-netns.sh"
      ignore_errors: yes
      register: vrf1_netns_result

    - debug:
        msg: "{{ vrf1_netns_result.stdout_lines | default([]) }}"


    - name: build Vrf2 network namespace connected to 10-leaf Ethernet12
      command: "files/vrf2-netns.sh"
      ignore_errors: yes
      register: vrf2_netns_result

    - debug:
        msg: "{{ vrf2_netns_result.stdout_lines | default([]) }}"

