kind: ConfigMap
apiVersion: v1
metadata:
  name: telegraf-sonic-config
  namespace: jalapeno
  selfLink: /api/v1/namespaces/jalapeno/configmaps/telegraf-sonic-config
data:
  telegraf.conf: |
    [agent]
      interval = "10s"
      round_interval = true
      metric_buffer_limit = 10000
      flush_buffer_when_full = true
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      debug = false
      quiet = false
      hostname = "telegraf"

    [[inputs.gnmi]]
      addresses = [
        "172.20.6.192:8080",
        "172.20.6.193:8080",
        "172.20.6.194:8080",
        "172.20.6.195:8080",
        "172.20.6.128:8080",
        "172.20.6.129:8080",
        "172.20.6.130:8080",
        "172.20.6.131:8080"
      ]
      redial = "10s"
      encoding = "json"
      origin = "openconfig"
      username = "admin"
      password = "admin"
      [[inputs.gnmi.subscription]]
        name = "interfaces"
        origin = "openconfig"
        path = "/interfaces/interface"
        subscription_mode = "sample"
        sample_interval = "10s"
      [[inputs.gnmi.subscription]]
        name = "system"
        origin = "openconfig"
        path = "/system"
        subscription_mode = "sample"
        sample_interval = "10s"
      [[inputs.gnmi.subscription]]
        name = "bgp_peers"
        origin = "openconfig"
        path = "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor"
        subscription_mode = "sample"
        sample_interval = "10s"
      [[inputs.gnmi.subscription]]
        name = "bgp_prefixes"
        origin = "openconfig"
        path = "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/ipv4-unicast/prefixes"
        subscription_mode = "sample"
        sample_interval = "10s"

    [[outputs.kafka]]
      brokers = ["broker.jalapeno.svc:9092"]
      topic = "jalapeno.sonic"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-sonic-deployment
  namespace: jalapeno
  labels:
    app: telegraf-sonic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-sonic
  template:
    metadata:
      labels:
        app: telegraf-sonic
    spec:
      containers:
        - name: telegraf
          image: docker.io/library/telegraf:1.34.2
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-sonic-config
              subPath: telegraf.conf
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: telegraf-sonic-config
          configMap:
            name: telegraf-sonic-config

---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-sonic-np
  namespace: jalapeno
spec:
  type: NodePort
  ports:
  - name: 57400-tcp
    port: 57400
    nodePort: 32401
    targetPort: 57400
  selector:
    app: telegraf-sonic