---

# ansible-playbook -i hosts clab-deploy-pbk.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv      

- name: Start logging
  hosts: localhost
  become: false
  tasks:
      
    - name: deploy.log start message
      become: false
      lineinfile:
        path: "/home/cisco/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Start containerlab topology deploy script"
        create: yes
      delegate_to: localhost
      
- name: Deploy sonic-vpp topology
  hosts: localhost
  become: true
  tasks: 
      
    - name: Clean out clab directory and files
      command: "rm -r clab-sonic/"
      args:
        chdir: ../
      ignore_errors: yes

    - name: Execute "clab deploy -t sonic.yaml" - this task may take 30-45 seconds to complete
      command: "clab deploy -t sonic.yaml"
      args:
        chdir: ../
      ignore_errors: yes
      register: clab_out

    - name: deploy.log containerlab / sonic status
      become: false
      lineinfile:
        path: "../deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: deploy script complete"
        create: yes
      delegate_to: localhost

    - name: reset user/group permissions on repo folders 
      command: "chown -R cisco:cisco ../../../../srv6-ai-fabric"
      ignore_errors: yes

    - name: clab deploy complete
      become: false
      lineinfile:
        path: "../deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Deploy script complete for {{ inventory_hostname }}"
        create: yes
      delegate_to: localhost

    - name: Wait for 150 seconds for sonic nodes to boot
      pause:
        seconds: 150

- name: Run sonic playbook
  import_playbook: sonic-pbk.yaml
  vars:
    ansible_user: admin
    ansible_ssh_pass: admin
    ansible_become_pass: admin
  ignore_errors: yes