---

# ansible-playbook -i hosts deploy-playbook.yml -e "ansible_user=admin ansible_ssh_pass=admin ansible_sudo_pass=admin" -vv
      
# - name: Start logging
#   hosts: localhost
#   become: false
#   tasks:
      
#     - name: deploy.log start message
#       become: false
#       lineinfile:
#         path: "/home/cisco/deploy.log"
#         line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Start containerlab topology deploy script"
#         create: yes
#       delegate_to: localhost
      
# - name: Deploy sonic-vpp topology
#   hosts: localhost
#   become: true
#   tasks: 
      
#     - name: Execute "clab deploy -t sonic-topo.yaml" - this task may take 30-45 seconds to complete
#       command: "clab deploy -t sonic-topo.yaml"
#       args:
#         chdir: ../
#       ignore_errors: yes
#       #register: clab_out

#     - name: deploy.log containerlab / sonic status
#       become: false
#       lineinfile:
#         path: "/home/cisco/deploy.log"
#         line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: deploy script complete"
#         create: yes
#       delegate_to: localhost

#     - name: reset user/group permissions on repo folders 
#       command: "chown -R cisco:cisco ../../../../srv6-ai-fabric"
#       ignore_errors: yes

#     - name: clab deploy complete
#       become: false
#       lineinfile:
#         path: "/home/cisco/deploy.log"
#         line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Deploy script complete for {{ inventory_hostname }}"
#         create: yes
#       delegate_to: localhost

#     - name: Wait for 150 seconds for sonic nodes to boot
#       pause:
#         seconds: 150

- name: Apply sonic configs
  hosts: sonic-nodes
  become: true
  tasks:

    - name: Copy config_db.json files
      copy:
        src: "{{ inventory_hostname }}/numbered/config_db.json"
        dest: "/etc/sonic/config_db.json"
        mode: 0644

    - name: sonic config load
      command: "sudo config load /etc/sonic/config_db.json -y"
      ignore_errors: yes

    - name: restart hostname service
      command: sudo systemctl restart hostname-config
      ignore_errors: yes

    - name: Copy loopback shell script
      copy:
        src: "{{ inventory_hostname }}/loopback.sh"
        dest: "/etc/sonic/loopback.sh"
        mode: 0755

    - name: run loopback shell script
      command: "/etc/sonic/loopback.sh"
      ignore_errors: yes

    - name: Save sonic configuration
      command: "sudo config save -y"
      ignore_errors: yes

    - name: Wait for 30 seconds for swss reset
      pause:
        seconds: 30

# BGP
    - name: Create a backup of the existing FRR file
      command: mv /etc/sonic/frr/bgpd.conf /etc/sonic/frr/bgpd.conf.bak
      args:
        creates: /etc/sonic/frr/bgpd.conf.bak
      ignore_errors: yes
      register: backup_result

    - name: Copy frr config files
      copy:
        src: "{{ inventory_hostname }}/numbered/frr.conf"
        dest: "/etc/sonic/frr/bgpd.conf"
        mode: 0644

    - name: Load the FRR config through vtysh
      command: vtysh -f /etc/sonic/frr/bgpd.conf
      ignore_errors: yes
      register: frr_load_result