frr defaults traditional
hostname 08-leaf
fpm address 127.0.0.1
ipv6 forwarding
no fpm use-next-hop-groups
service integrated-vtysh-config
ipv6 route fc00:0:8::/48 Loopback0
!
route-map BGP-IPV6 permit 20
set ipv6 next-hop prefer-global
exit
!
vrf Vrf1
 ipv6 route fc00:0:f800:6::/64 Vrf1 segments fc00:0:4:2:6:10:fe08::
exit-vrf
!
no router bgp 65100
router bgp 65008
bgp router-id 10.0.0.8
bgp log-neighbor-changes
no bgp ebgp-requires-policy
no bgp default ipv4-unicast
no bgp network import-check
bgp bestpath as-path multipath-relax
neighbor 2001:db8:1:1::18 remote-as 65001
neighbor 2001:db8:1:1::22 remote-as 65001
!
address-family ipv6 unicast
network fc00:0:8::/48
network fc00:0:8::1/128
neighbor 2001:db8:1:1::18 activate
neighbor 2001:db8:1:1::18 route-map BGP-IPV6 in
neighbor 2001:db8:1:1::22 activate
neighbor 2001:db8:1:1::22 route-map BGP-IPV6 in
maximum-paths 64
exit-address-family
exit
!
segment-routing
 srv6
  encapsulation
   source-address fc00:0:8::1
  locators
   locator MAIN
    prefix fc00:0:8::/48
    format usid-f3216
    opcode ::fe00:0:0:0:0 uA interface Ethernet0
    opcode ::fe04:0:0:0:0 uA interface Ethernet4
    opcode ::fe08:0:0:0:0 uA interface Ethernet8
    opcode ::fe12:0:0:0:0 uA interface Ethernet12
   exit
   !
  exit
  !
 exit
 !
exit
!
end