---

# ansible-playbook -i hosts destroy-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv
      
- name: Start logging
  hosts: localhost
  become: false
  tasks:
      
    - name: destroy.log start message
      become: false
      lineinfile:
        path: "/home/cisco/destroy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: destroy containerlab topology and k8s vms"
        create: yes
      delegate_to: localhost

- name: shutdown sonic vxr topology
  hosts: localhost
  become: true
  tasks: 
      
    - name: Execute "vxr stop" - this task may take 15-30 seconds to complete
      command: "vxr stop"
      args:
        chdir: ../
      ignore_errors: yes
      #register: vxr_out

    - name: clean out clab directory and files
      command: "vxr clean"
      args:
        chdir: ../
      ignore_errors: yes
      #register: clean_out
