---

- name: Copy ansible hosts entries to /etc/hosts
  hosts: localhost
  become: true
  tasks:

    - name: Copy config_db.json files
      copy:
        src: "{{ inventory_hostname }}/numbered/config_db.json"
        dest: "/etc/sonic/config_db.json"
        mode: 0644