kind: ConfigMap
apiVersion: v1
metadata:
  name: telegraf-ingress-config
  namespace: jalapeno
  selfLink: /api/v1/namespaces/jalapeno/configmaps/telegraf-ingress-config
data:
  telegraf.conf: |
    [agent]
      interval = "10s"
      round_interval = true
      metric_buffer_limit = 10000
      flush_buffer_when_full = true
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      debug = false
      quiet = false
      hostname = "telegraf"

    [[inputs.cisco_telemetry_mdt]]
      transport = "grpc"
      service_address = ":57400"
      embedded_tags = ["Cisco-IOS-XR-fib-common-oper:mpls-forwarding/nodes/node/label-fib/forwarding-details/forwarding-detail/label-information/outgoing-interface"]
      [inputs.cisco_telemetry_mdt.aliases]
        ifstats = "ietf-interfaces:interfaces-state/interface/statistics"

    [[outputs.kafka]]
      brokers = ["broker.jalapeno.svc:9092"]
      topic = "jalapeno.telemetry"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-ingress-deployment
  namespace: jalapeno
  labels:
    app: telegraf-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-ingress
  template:
    metadata:
      labels:
        app: telegraf-ingress
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.15-alpine
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-ingress-config
              subPath: telegraf.conf
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: telegraf-ingress-config
          configMap:
            name: telegraf-ingress-config

---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-ingress-np
  namespace: jalapeno
spec:
  type: NodePort
  ports:
  - name: 57400-tcp
    port: 57400
    nodePort: 32400
    targetPort: 57400
  selector:
    app: telegraf-ingress

